### ISSUE TITLE
Error on Author page.

### ISSUE THREAD

**Issue by bramderudder** [BD-Multimedia/BD-CMS#6]
I get 2 errors on the author page.

Notice: Undefined index: author in C:\Users\bram\Desktop\BDmultimedia\root\BD-CMS\author.php on line 4
Notice: Undefined variable: contentArray in C:\Users\bram\Desktop\BDmultimedia\root\BD-CMS\functions.php on line 40

**Comment by bderudder** [comment]
You are not supposed to surf to author.php without any ?author=... value
Now there is a security that you are redirected to the index page when there is no value

See Github updates for code changes
