### ISSUE TITLE
Error Editing article.

### ISSUE THREAD

**Issue by bramderudder** [BD-Multimedia/BD-CMS#7]
The page does not edit any new articles I submit.
And it gives me these errors after clicking the editbutton:

Notice: Undefined index: id in C:\Users\bram\Desktop\BDmultimedia\root\BD-CMS\backend\edit-article.php on line 5

Notice: Undefined offset: 0 in C:\Users\bram\Desktop\BDmultimedia\root\BD-CMS\functions.php on line 27
succes

What happens then is: it created a new article with the content that has been edited.

**Comment by bderudder** [comment]
Problem solved with last update see github for code changes
